inherit_gem:
  bixby: bixby_default.yml

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'spec/rails_helper.rb'
    - 'spec/**/*'
    - 'app/models/concerns/tufts/**/*'
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

RSpec/ExampleLength:
      Exclude:
        - 'spec/features/**/*'


