inherit_gem:
  bixby: bixby_default.yml

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'spec/rails_helper.rb'
    - 'spec/**/*'
    - 'app/models/concerns/tufts/**/*'
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
Metrics/LineLength:
   Exclude:
    - 'spec/controllers/tufts/draft_controller_spec.rb'
RSpec/ExampleLength:
   Exclude:
    - 'spec/features/**/*'
    - 'spec/controllers/tufts/draft_controller_spec.rb'
    - 'spec/lib/import_export/deposit_type_importer_spec.rb'
    - 'spec/lib/import_export/deposit_type_exporter_spec.rb'
    - 'spec/lib/deposit_types_controller_spec.rb'
    - 'spec/controllers/contribute_controller_spec.rb'
    - 'spec/controllers/deposit_types_controller_spec.rb'
RSpec/NestedGroups:
  Exclude:
   - 'spec/controllers/deposit_types_controller_spec.rb'
   - 'spec/controllers/contribute_controller_spec.rb'     
RSpec/AnyInstance:
  Exclude:
   - 'spec/controllers/deposit_types_controller_spec.rb'
   - 'spec/lib/deposit_types_controller_spec.rb'
RSpec/MultipleExpectations:
  Exclude:
  - 'spec/controllers/contribute_controller_spec.rb'