language: ruby
sudo: false
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.3.3
  - 2.3.4
before_script:
  - bundle exec sidekiq -d -l /tmp/sidekiq.log
  - bundle exec rails db:setup
script:
  - bundle exec rake
addons:
  apt:  
    packages:
     - imagemagick
services:
  - redis-server

