language: ruby
sudo: false
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.3.3
  - 2.3.4

before_script:
  - bundle exec rails db:setup
script:
  - bundle exec rake
services:
  - redis-server
