language: ruby
sudo: false
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.3.3
  - 2.3.4

before_script:
  - bundle exec rake db:create
script:
  - bundle exec rake

services:
  - redis-server
