# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b68f50877407fb13fb5bbdf08ea7bc5365124c71228e1535ed859aa0f84341b9e5f9de091f08f336d2917298cfced210e24fbcd46c82c6621987f3636572c6a

test:
  secret_key_base: f562017e4f0f144349782b382d0703b093624c36c1c1074e9a46c138df7904172835b13d4631b8d134db4b8bbc85a297bcabb30f38c4f37ae8bf640be0cd2cd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
