---
:queues:
  - [ingest, 4]
  - [batch, 2]
  - [handle, 1]
  - [default, 1]
  - [tdr_derivative_queue, 3]

:limits:
  tdr_derivative_queue: 3
  ingest: 5
  batch: 5
  handle: 5
  default: 5

test:
  :concurrency: 5

development:
  :concurrency: 5

stage:
  :concurrency: 3

production:
  :concurrency: 3
